# Generated by Django 2.1.3 on 2018-11-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_cliente_email'),
        ('alugueis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='cliente',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente'),
            preserve_default=False,
        ),
    ]
