# Generated by Django 2.1.3 on 2018-11-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('modelo', models.CharField(max_length=60)),
                ('cor', models.CharField(max_length=15)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('renavam', models.CharField(max_length=11)),
            ],
        ),
    ]
