# Generated by Django 2.1.3 on 2018-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60)),
                ('cor', models.CharField(max_length=15)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('renavam', models.CharField(max_length=11, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
