# Generated by Django 2.1.3 on 2018-11-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_auto_20181122_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
