# Generated by Django 2.1.3 on 2018-11-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_auto_20181129_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='renavam',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
