# Generated by Django 2.1.3 on 2018-11-26 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
                ('nome_mae', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('rg', models.CharField(max_length=9)),
                ('cnh', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
