# Generated by Django 2.1.3 on 2018-11-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('clientes', '0002_auto_20181126_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
