# Generated by Django 2.1.3 on 2018-11-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='group',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
    ]
