# Generated by Django 2.1.3 on 2018-11-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20181127_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
