# Generated by Django 2.1.3 on 2018-11-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20181127_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enderecos.Endereco'),
        ),
    ]
