# Generated by Django 2.1.3 on 2018-11-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20181127_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnh',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
