# Generated by Django 2.1.3 on 2018-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=60)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('cidade', models.CharField(max_length=60)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
    ]
