# Generated by Django 2.1.3 on 2018-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
